import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/assets/globals.css";
import { Navigation } from "@/components/_navigation";

const nohemiRegular = localFont({
  src: [
    {
      path: "./_fonts/nohemi/light.woff",
      weight: "300",
    },
    {
      path: "./_fonts/nohemi/regular.woff",
      weight: "400",
    },
    {
      path: "./_fonts/nohemi/semibold.woff",
      weight: "600",
    },
    {
      path: "./_fonts/nohemi/bold.woff",
      weight: "700",
    },
    {
      path: "./_fonts/nohemi/extrabold.woff",
      weight: "900",
    },
  ],
  variable: "--font-nohemi-sans",
});

const geistMono = localFont({
  src: "./_fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nohemiRegular.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-full overflow-auto font-[family-name:var(--font-nohemi-sans)] p-6 scroll-smooth">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
