import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import "@/src/assets/globals.css";
import { Navigation } from "@/src/components/layout/navigation";
import { Footer } from "@/src/components/layout/footer";
const nohemiRegular = localFont({
  src: [
    {
      path: "../assets/fonts/nohemi/light.woff",
      weight: "300",
    },
    {
      path: "../assets/fonts/nohemi/regular.woff",
      weight: "400",
    },
    {
      path: "../assets/fonts/nohemi/semibold.woff",
      weight: "600",
    },
    {
      path: "../assets/fonts/nohemi/bold.woff",
      weight: "700",
    },
    {
      path: "../assets/fonts/nohemi/extrabold.woff",
      weight: "900",
    },
  ],
  variable: "--font-nohemi-sans",
});

const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nohemiRegular.variable} ${geistMono.variable} antialiased`}
      >
        <div
          id="content-wrapper"
          className="h-screen w-full overflow-auto font-[family-name:var(--font-nohemi-sans)] p-6 scroll-smooth"
        >
          <Navigation />
          {children}
          <Footer />
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
